// course-react/05-react-basics/demo/react-todo/src/TodoItem.tsx
import { ITodo } from './types.js'

interface Props {
  todo: ITodo
  onToggle: () => void
  onDelete: () => void
}

export default class TodoItem extends React.Component<Props> {
  render() {
    return (
      <div className={this.props.todo.finished ? "todo-item todo-finished" : "todo-item"}>
        <i className="iconfont icon-checkbox" onClick={this.props.onToggle} />
        <span className="todo-title">{this.props.todo.content}</span>
        <i className="iconfont icon-delete" onClick={this.props.onDelete} />
      </div>
    )
  }
}

// course-hubu/05-vue-basic/demo/vue-todo/src/components/TodoItem.vue
<template>
  <div :class="todo.finished ? 'todo-item todo-finished' : 'todo-item'">
    <i class="iconfont icon-checkbox" @click="onToggle" />
    <span class="todo-title">{{ todo.content }}</span>
    <i class="iconfont icon-delete" @click="onDelete" />
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";
import { ITodo } from "../types";

export default defineComponent({
  name: "TodoItem",
  props: {
    todo: { type: Object as PropType<ITodo>, required: true },
    onToggle: Function as PropType<() => void>,
    onDelete: Function as PropType<() => void>,
  },
});
</script>
