// tianzexiang/tasks/pre-task02/todo/src/pages/Todo/components/TodoItem/index.tsx
import { CheckBoxIcon, DeleteIcon, Item, Title } from './styled'
import { ITodo } from '../../../../interfaces/todo'

interface TodoItemProps {
  todo: ITodo
  key: string | number
  changeTodoStat(id: string): void
  deleteTodo(id: string): void
}

function TodoItem(props: TodoItemProps) {
  const { todo, changeTodoStat, deleteTodo } = props
  return (
    <Item>
      <CheckBoxIcon
        className="iconfont icon-checkbox"
        isFinished={todo.finished}
        onClick={() => changeTodoStat(todo.id)}
      />
      <Title isFinished={todo.finished}>{todo.content}</Title>
      <DeleteIcon
        className="iconfont icon-delete"
        onClick={() => deleteTodo(todo.id)}
      />
    </Item>
  )
}
export default TodoItem

// course-hubu/05-vue-basic/demo/vue-todo/src/components/TodoItem.vue
<template>
  <div :class="todo.finished ? 'todo-item todo-finished' : 'todo-item'">
    <i class="iconfont icon-checkbox" @click="onToggle" />
    <span class="todo-title">{{ todo.content }}</span>
    <i class="iconfont icon-delete" @click="onDelete" />
  </div>
</template>

<script lang="ts">
import { defineComponent, PropType } from "vue";
import { ITodo } from "../types";

export default defineComponent({
  name: "TodoItem",
  props: {
    todo: { type: Object as PropType<ITodo>, required: true },
    onToggle: Function as PropType<() => void>,
    onDelete: Function as PropType<() => void>,
  },
});
</script>
