// tianzexiang/tasks/pre-task03/src/pages/HotNews/index.tsx
import NewsCard from './components/NewsCard'
import { getNews } from '@/api/article'
import { useState, useEffect } from 'react'
import { IArticle } from '@/interfaces/article'
import { useNavigate } from 'react-router-dom'
import { PagePathEnum } from '@/enums/pageEnum'

function HotNews() {
  const [newsList, setNewsList] = useState<IArticle[]>([])
  const navigate = useNavigate()
  const handleGetNewsList = async () => {
    try {
      const res = await getNews()
      setNewsList(res.rows)
    } catch (err) {}
  }

  useEffect(() => {
    handleGetNewsList()
  }, [])

  const handleCardClick = (id: string) => {
    navigate(PagePathEnum.DETAIL.replace(':id', id))
  }

  return (
    <>
      {newsList.map((news) => (
        <NewsCard
          news={news}
          key={news.id}
          onClick={(id) => handleCardClick(id)}
        />
      ))}
    </>
  )
}
export default HotNews

// essay/tasks/week-07/src/views/hot-news/HotNews.vue
<script lang='ts' setup>
import { ref, onBeforeMount } from 'vue'
import { news } from '@/services/api'
import NewsCard from './components/NewsCard.vue'
import { useRouter } from 'vue-router'
import type { IArticle } from '@/interfaces/types'
import { PageNameEnum } from '@/enums/pageEnum'

const newsList = ref<IArticle[]>()
const router = useRouter()
const getNewsList = async () => {
  try {
    const res = await news()
    if (res.stat === 'OK') {
      newsList.value = res.rows
    }
  } catch (err) {
    window.alert(err)
  }
}

// 点击跳转详情
const handleClick = (id: string) => {
  router.push({ name: PageNameEnum.DETAIL, params: { id } })
}

onBeforeMount(() => {
  getNewsList()
})
</script>
<template>
  <NewsCard v-for="item in newsList" :key="item.id" :news="item" @click="handleClick"/>
</template>
<style scoped>
</style>
