// tianzexiang/tasks/pre-task03/src/pages/GoodArticle/index.tsx
import ArticleCard from './components/ArticleCard'
import { getPosts } from '@/api/article'
import { useState, useEffect } from 'react'
import { IArticle } from '@/interfaces/article'
import { useNavigate } from 'react-router-dom'
import { PagePathEnum } from '@/enums/pageEnum'

function GoodArticle() {
  const [articleList, setArticleList] = useState<IArticle[]>([])
  const navigate = useNavigate()
  const handleGetArticleList = async () => {
    try {
      const res = await getPosts()
      setArticleList(res.rows)
    } catch (err) {}
  }

  useEffect(() => {
    handleGetArticleList()
  }, [])

  const handleCardClick = (id: string) => {
    navigate(PagePathEnum.DETAIL.replace(':id', id))
  }
  return (
    <>
      {articleList.map((article, index) => (
        <ArticleCard
          article={article}
          key={article.id}
          rank={index + 1}
          onClick={(id) => handleCardClick(id)}
        />
      ))}
    </>
  )
}
export default GoodArticle

// essay/tasks/week-07/src/views/good-article/GoodArticle.vue
<script lang='ts' setup>
import ArticleCard from './components/ArticleCard.vue'
import { posts } from '@/services/api'
import { onBeforeMount, ref } from 'vue'
import { useRouter } from 'vue-router'
import type { IArticle } from '@/interfaces/types'
import { PageNameEnum } from '@/enums/pageEnum'

const articleList = ref<IArticle[]>([])
const router = useRouter()
// 获取所有文章
const getArticleList = async () => {
  try {
    const res = await posts()
    if (res.stat === 'OK') {
      articleList.value = res.rows
    }
  } catch (err) {
    window.alert(err)
  }
}

// 点击跳转详情
const handleClick = (id: string) => {
  router.push({ name: PageNameEnum.DETAIL, params: { id } })
}

onBeforeMount(() => {
  getArticleList()
})
</script>
<template>
  <ArticleCard v-for="(item, index) in articleList" :key="item.id" :article="item" :rank="index + 1"
    @click="handleClick" />
</template>
<style scoped>
</style>
