// essay/tasks/week-06/components-practice/src/App.vue
<script lang='ts' setup>
import CustomButton from './components/custom-button/CustomButton.vue'
import CustomModal from './components/custom-modal/CustomModal.vue'
import { ref } from 'vue'
const modalVisible = ref(false)
const handleClick = () => {
  modalVisible.value = true
}
</script>
<template>
  <div class="btn-box">
    <CustomButton type="default" @click="handleClick">打开modal</CustomButton>
    <CustomButton type="primary" @click="handleClick">打开modal</CustomButton>
  </div>
  <CustomModal v-model:visible="modalVisible"></CustomModal>
</template>
<style scoped>
* {
  margin: 0;
  padding: 0;
}
.btn-box{
  padding-top: 100px;
  display: flex;
  justify-content: center;
  gap: 40px;
}
</style>

// tianzexiang/tasks/pre-task02/components-practice/src/App.tsx
import CustomButton from './components/CustomButton'
import CustomModal from './components/CustomModal'
import { useState } from 'react'
import styled from 'styled-components'

const ButtonWrap = styled.div`
  display: flex;
  gap: 10px;
`

function App() {
  const [modalVisible, setModalVisible] = useState(false)
  const handleClick = (visible: boolean) => {
    setModalVisible(visible)
  }

  const handleClose = () => {
    console.log('close')
  }

  const handleConfirm = () => {
    console.log('confirm');
    
  }
  return (
    <div>
      <ButtonWrap>
        <CustomButton type="default" onClick={() => handleClick(false)}>
          隐藏modal
        </CustomButton>
        <CustomButton type="primary" onClick={() => handleClick(true)}>
          显示modal
        </CustomButton>
      </ButtonWrap>
      <CustomModal
        modalVisible={modalVisible}
        setModalVisible={setModalVisible}
        onClose={handleClose}
        onConfirm={handleConfirm}
      ></CustomModal>
    </div>
  )
}

export default App
