// essay/tasks/week-06/todo/src/views/todo/components/TodoInput.vue
<script lang='ts' setup>
import { ref } from 'vue'

const inputContent = ref('')
// eslint-disable-next-line func-call-spacing
const emits = defineEmits<{
  (e: 'createTodo', content: string): void
}>()
const createTodo = () => {
  if (inputContent.value.trim() !== '') emits('createTodo', inputContent.value)
}
</script>
<template>
  <input id="input" type="text" class="input" placeholder="What needs to be done?" autocomplete="off"
    v-model="inputContent" @keydown.enter="createTodo">
</template>
<style scoped>
.input {
  width: 100%;
  height: 50px;
  padding: 0 10px;
  border: 1px solid #ccc;
  border-radius: 5px;
  outline: none;
  font-size: 18px;
  color: #333;
}
</style>

// tianzexiang/tasks/pre-task02/todo/src/pages/Todo/components/TodoInput/index.tsx
import { Input } from './styled'
import { useState, KeyboardEvent } from 'react'

interface ITodoInputProps {
  createTodo(content: string): void
}

function TodoInput(props: ITodoInputProps) {
  const { createTodo } = props
  const [content, setContent] = useState('')

  const handleKeyPress = (content: string, e: KeyboardEvent) => {
    if (e.key === 'Enter') {
      createTodo(content)
    }
  }
  return (
    <Input
      value={content}
      onChange={(e) => setContent(e.target.value)}
      type="text"
      placeholder="What needs to be done?"
      autoComplete="off"
      onKeyDown={(e) => handleKeyPress(content, e)}
    />
  )
}

export default TodoInput
