// tianzexiang/tasks/pre-task03/src/pages/GoodArticle/components/ArticleCard/index.tsx
import {
  CardWrapper,
  Cover,
  CoverImg,
  RankImg,
  Title,
  InfoWrapper,
  Info,
  CommentWrapper,
  CommentIcon,
  Comment,
  FavorWrapper,
  FavorIcon,
  Favor,
} from './styled'
import type { IArticle } from '@/interfaces/article'
import { MouseEvent } from 'react'

interface ArticleCardProps {
  article: IArticle
  key: string | number
  rank?: number | string
  onClick?: (id: string, evt: MouseEvent) => void
}

function ArticleCard(props: ArticleCardProps) {
  const { article, rank = '1' , onClick} = props
  const getRankImgURL = (rank: string | number) => require(`@/assets/images/rank-top${rank}.png`)
  return (
    <CardWrapper  onClick={(e) => (onClick ? onClick(article.id, e) : undefined)}>
      {/* 封面 */}
      <Cover>
        <CoverImg src={article.banner} />
        {Number(rank) <= 5 ? <RankImg src={getRankImgURL(rank)} /> : ''}
      </Cover>
      {/* 标题 */}
      <Title>{article.title}</Title>
      {/* 其他信息 */}
      <InfoWrapper>
        <Info>
          {/* 评论 */}
          <CommentWrapper>
            <CommentIcon className="iconfont icon-pinglun" />
            <Comment>{article.comments}</Comment>
          </CommentWrapper>
          {/* 点赞 */}
          <FavorWrapper>
            <FavorIcon className="iconfont icon-dianzan" />
            <Favor>{article.likes}</Favor>
          </FavorWrapper>
        </Info>
      </InfoWrapper>
    </CardWrapper>
  )
}
export default ArticleCard

// essay/tasks/week-07/src/views/good-article/components/ArticleCard.vue
<script lang='ts' setup>
import { ref, reactive } from 'vue'
import type { IArticle } from '@/interfaces/types'

const props = withDefaults(defineProps<{
  article: IArticle
  rank?: string | number
}>(), {
  rank: '1'
})
// eslint-disable-next-line func-call-spacing
const emit = defineEmits<{
  (e: 'click', id: string, evt: MouseEvent): void
}>()

const article = reactive(props.article)
const rank = ref(props.rank)
// 获取rank图片
const getRankImgURL = (rank: string | number) => require(`@/assets/images/rank-top${rank}.png`)
const handleClick = (evt: MouseEvent) => emit('click', article.id, evt)
</script>
<template>
  <div href="#" class="card-sku" @click="handleClick">
    <div class="cover">
      <img class="img" :src="article.banner" alt="动漫" title="动漫" />
      <img v-if="Number(rank) <= 5" class="rank" :src="getRankImgURL(rank)" />
    </div>
    <div class="outline">
      {{article.title}}
    </div>
    <div class="info">
      <div class="comment_favor">
        <div>
          <i class="iconfont icon-pinglun"></i>
          <span class="comment"> {{ article.comments }} </span>
        </div>
        <div>
          <i class="iconfont icon-dianzan"></i>
          <span class="favor">{{ article.likes }}</span>
        </div>
      </div>
    </div>
  </div>
</template>
<style scoped>
.card-sku {
  position: relative;
  display: block;
  background-color: #fff;
  border-radius: 10px;
  padding: 15px;
  width: 100%;
  cursor: pointer;
}

.cover {
  width: 100%;
  border-radius: 5px;
  overflow: hidden;
  position: relative;
}

.cover>.img {
  width: 100%;
  border-radius: 5px;
}

.cover>.rank {
  position: absolute;
  width: 12%;
  left: 0;
  right: 0;
}

.outline {
  color: #000;
  font-size: 1rem;
  font-weight: bold;
  margin: 15px 0;
}

.info {
  display: flex;
  align-items: center;
}

.comment_favor {
  flex: 1;
  display: flex;
  gap: 20px;
  font-size: 0.75rem;
  color: #b6b6b6;
  justify-content: flex-end;
  align-items: center;
  margin-right: 15px;
  white-space: nowrap;
  letter-spacing: .05rem;
}

.comment,
.favor {
  margin-left: 5px;
}
</style>
